# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/general_store_db
spring.datasource.username=root
spring.datasource.password=abhishek6209

# Hibernate Settings (Builds the tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true